# Generated by Django 3.1.1 on 2021-01-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videodata_thimnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recently',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
                ('thimnail', models.ImageField(blank=True, upload_to='Thumnail')),
                ('video_length', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
                ('thimnail', models.ImageField(blank=True, upload_to='Thumnail')),
                ('video_length', models.IntegerField(blank=True)),
            ],
        ),
    ]
