# Generated by Django 3.1.1 on 2021-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recently_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_logo', models.ImageField(upload_to='logo')),
                ('notification', models.ImageField(upload_to='notification')),
            ],
        ),
    ]
